# Generated by Django 3.2.1 on 2021-05-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0002_auto_20210506_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcut',
            old_name='category_id',
            new_name='category',
        ),
    ]
