# Generated by Django 3.2.1 on 2021-05-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0003_rename_category_id_shortcut_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='shortcut',
            old_name='icon_path',
            new_name='icon_class',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='fa-button', max_length=2048),
            preserve_default=False,
        ),
    ]
