# Generated by Django 3.2.1 on 2021-05-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of site-wide variable', max_length=200)),
                ('value', models.CharField(blank=True, help_text='Value of site-wide variable that scripts can reference - must be valid JSON', max_length=2000, null=True)),
            ],
        ),
    ]
