# Generated by Django 3.2.1 on 2021-05-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(help_text='Key of site-wide variable', max_length=200),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, help_text='Value of site-wide variable that scripts can reference', max_length=2000, null=True),
        ),
    ]
