# Generated by Django 3.2.1 on 2021-05-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210506_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='key',
            field=models.CharField(default='site_title', help_text='Key of site-wide variable', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(help_text='Name of site-wide variable', max_length=200),
        ),
    ]
